; Listing generated by Microsoft (R) Optimizing Compiler Version 19.39.33519.0 

	TITLE	C:\homework\demo1\Debug\demo.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__FE09AF47_concurrencysal@h DB 01H
__C073CA79_sal@h DB 01H
__D6AFE870_vadefs@h DB 01H
__D63E96CF_vcruntime@h DB 01H
__1B0272D9_corecrt@h DB 01H
__44420885_corecrt_stdio_config@h DB 01H
__AB601D8D_corecrt_wstdio@h DB 01H
__C1EC35D3_stdio@h DB 01H
__C6BF8DC5_demo@c DB 01H
msvcjmc	ENDS
PUBLIC	_main
PUBLIC	__JustMyCode_Default
EXTRN	__imp__putchar:PROC
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\homework\demo1\demo.c
;	COMDAT _main
_TEXT	SEGMENT
tv71 = -229						; size = 1
_i$1 = -32						; size = 4
_row$2 = -20						; size = 4
_ch$ = -5						; size = 1


;下面为主要代码区
;函数序言（栈帧与本地变量铺垫）
_main	PROC						; COMDAT

; 2    : int main(void) {

	push	ebp
	mov	ebp, esp
	sub	esp, 232				; 000000e8H  ; 给本地变量留出 232 字节栈空间
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-40]
	mov	ecx, 10					; 0000000aH  
	mov	eax, -858993460				; ccccccccH  ; VS 调试填充“CC”做未初始化检测
	rep stosd                                    ; 用 0xCC 填 ebp-40..(40字节)
	mov	ecx, OFFSET __C6BF8DC5_demo@c
	call	@__CheckForDebuggerJustMyCode@4

; 3    :     char ch = 'a';

	mov	BYTE PTR _ch$[ebp], 97			; 00000061H

; 4    :     for (int row = 0; row < 2; ++row) {

	mov	DWORD PTR _row$2[ebp], 0
	jmp	SHORT $LN4@main           ; 跳到条件检查
$LN2@main:                        ; 迭代末尾位置
	mov	eax, DWORD PTR _row$2[ebp]
	add	eax, 1
	mov	DWORD PTR _row$2[ebp], eax
$LN4@main:
	cmp	DWORD PTR _row$2[ebp], 2  ; row < 2 ?
	jge	SHORT $LN3@main           ; 否则跳出

; 5    :         for (int i = 0; i < 13; ++i) {

	mov	DWORD PTR _i$1[ebp], 0
	jmp	SHORT $LN7@main
$LN5@main:
	mov	eax, DWORD PTR _i$1[ebp]
	add	eax, 1
	mov	DWORD PTR _i$1[ebp], eax
$LN7@main:
	cmp	DWORD PTR _i$1[ebp], 13			; 0000000dH
	jge	SHORT $LN6@main

; 6    :             putchar(' ');

	mov	esi, esp
	push	32					; 00000020H  ; 参数：' '
	call	DWORD PTR __imp__putchar         ; 调用 CRT 的 putchar
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp                   ; /RTC 检查调用前后 ESP 是否一致

; 7    :             putchar(ch++);

	mov	al, BYTE PTR _ch$[ebp]               ; 取 ch
	mov	BYTE PTR tv71[ebp], al               ; 临时保存“旧值” → 对应 ch++
	mov	cl, BYTE PTR _ch$[ebp]
	add	cl, 1                                ; ch = ch + 1（完成 ch++ 的“自增”部分）
	mov	BYTE PTR _ch$[ebp], cl               ; sign-extend '旧值' → 参数
	movsx	edx, BYTE PTR tv71[ebp]
	mov	esi, esp
	push	edx
	call	DWORD PTR __imp__putchar         ; 用“旧值”作为参数调用 putchar
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp

; 8    :         }

	jmp	SHORT $LN5@main
$LN6@main:

; 9    :         putchar('\n');

	mov	esi, esp
	push	10					; 0000000aH   ; '\n'
	call	DWORD PTR __imp__putchar
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp

; 10   :     }

	jmp	SHORT $LN2@main
$LN3@main:

; 11   :     return 0;

	xor	eax, eax              ; 返回 0

; 12   : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 232				; 000000e8H  ; 释放本地变量空间
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
